# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb221d94c7cdd7ca92fa2e507c435f017b048bf687c3ac30e87c810a1de9134a599e62c959c60179bdee35eaa19ed791fcffc2dcd8899fb5724962ca9624d67b

test:
  secret_key_base: 51d95fc51a662f8a8ad64b2479696994941fea43da8ef76c7b9c4cd1eb9da11e45d49ad5b654fbbe582d891f78699d15f08275a6889296d1f4c45ca360781fec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
